### ISSUE TITLE
Could not parse units

### ISSUE THREAD

**Issue by kant2002** [FirelyTeam/Fhir.Metrics#4]
This is measurement unit which I try to parse `mL/min/1.73`
Code:
```
var system = UCUM.Load();
var mu = system.Metric("mL/min/1.73");
```
Error:
`'Unknown Unit or prefix in expression '1''`

So my question is, should I somehow register 1.73 as a Unit, or do something else? On the https://lhncbc.github.io/ucum-lhc/demo.html this unit is measured as valid unit.

**Comment by kant2002** [comment]
Not sure my previous example, but `%{baseline}` looks like perfectly valid UCUM code and it is don't recognized too.

**Comment by alexzautke** [comment]
Partially fixed by PR #9 
`%{baseline}` should work now as support for annotations was added.
The issue remains that this library does not accept any term in a multiplication when trying to parse a metric.

**Comment by alexzautke** [comment]
I know this issue is open for quite a while, but did you actually meant to create a metric with "mL/min/1.73" and not "mL/min/{1.73_m2}"? In theory it is of course allowed to have multiplication of 1 x 73 in the last denominator, though having a unit different than 1 does not have a valid semantic meaning in most cases. Therefore, the question is if we should keep the behaviour of the current develop version and only allow 1 as unit and not arbitrary numeric units.

**Comment by kant2002** [comment]
I take these values from the existing database. Maybe it is not strictly correct behavior for UCUM code, but that's what I see people wrote, and that make sense to me to have. even if I have to normalize. That's what I able to recall regarding that issue. Does that helps, or you need additional information?
